version: "3.8"

services:
  resume-recommender:
    build:
      context: .
      dockerfile: Dockerfile
    image: resume-recommender:latest
    container_name: resume-recommender-prod
    ports:
      - "80:8501" # Map to port 80 for production
    env_file:
      - .env
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - resume-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Add nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: resume-nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - resume-recommender
    restart: unless-stopped
    networks:
      - resume-net
    profiles:
      - production

networks:
  resume-net:
    driver: bridge

volumes:
  uploads:
    driver: local
  logs:
    driver: local
